# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

stages:
  - build
  - deploy
services:
  - docker:dind

build-master:
  stage: build
  script:
    - export DOCKER_HOST=$DOCKER_PORT
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

deploy-master:
  stage: deploy
  image: alpine
  environment:
    name: deploy
  script:
    - apk add --no-cache gettext
    - apk update  && apk add --no-cache curl
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
    - chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl
    - mkdir -p $HOME/.kube
    - echo  -n $KUBECONFIG  > $HOME/.kube/config
    - kubectl create -n lliivvss secret docker-registry registry.gitlab.com --docker-server=$CI_REGISTRY --docker-username=$CI_REGISTRY_USER --docker-password=$CI_REGISTRY_PASSWORD --docker-email=$GITLAB_USER_EMAIL
    - kubectl version
    - kubectl config view
    - envsubst < deployment.yml |  kubectl apply -f -
    - kubectl delete secret registry.gitlab.com
  only:
    - master
